INFO 2020-01-02 14:21:13,711 autoreload 6057 4610153920 Watching for file changes with StatReloader
INFO 2020-01-02 14:22:52,063 autoreload 6057 4610153920 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:22:52,440 autoreload 6091 4594466240 Watching for file changes with StatReloader
INFO 2020-01-02 14:23:00,159 autoreload 6091 4594466240 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:23:00,506 autoreload 6095 4618206656 Watching for file changes with StatReloader
INFO 2020-01-02 14:23:12,531 autoreload 6095 4618206656 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:23:12,915 autoreload 6099 4516642240 Watching for file changes with StatReloader
INFO 2020-01-02 14:25:58,702 autoreload 6099 4516642240 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 14:25:59,081 autoreload 6133 4652862912 Watching for file changes with StatReloader
INFO 2020-01-02 14:26:38,435 autoreload 6133 4652862912 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 14:26:38,793 autoreload 6140 4735839680 Watching for file changes with StatReloader
INFO 2020-01-02 14:34:24,222 autoreload 6140 4735839680 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:34:24,596 autoreload 6191 4591623616 Watching for file changes with StatReloader
INFO 2020-01-02 14:34:50,816 autoreload 6191 4591623616 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:34:51,174 autoreload 6195 4612361664 Watching for file changes with StatReloader
INFO 2020-01-02 14:34:54,561 autoreload 6195 4612361664 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:34:54,965 autoreload 6200 4497198528 Watching for file changes with StatReloader
INFO 2020-01-02 14:35:44,992 autoreload 6200 4497198528 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 14:35:45,361 autoreload 6204 4715036096 Watching for file changes with StatReloader
INFO 2020-01-02 14:36:08,274 autoreload 6204 4715036096 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 14:36:08,639 autoreload 6222 4612124096 Watching for file changes with StatReloader
INFO 2020-01-02 14:36:29,412 autoreload 6222 4612124096 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 14:36:29,782 autoreload 6227 4454424000 Watching for file changes with StatReloader
INFO 2020-01-02 14:37:00,461 autoreload 6233 4388093376 Watching for file changes with StatReloader
INFO 2020-01-02 14:37:12,579 autoreload 6233 4388093376 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:37:12,925 autoreload 6236 4603387328 Watching for file changes with StatReloader
WARNING 2020-01-02 14:37:14,280 log 6236 123145429803008 Not Found: /board/1
WARNING 2020-01-02 14:37:14,281 basehttp 6236 123145429803008 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:37:35,712 log 6236 123145429803008 Not Found: /board/1
WARNING 2020-01-02 14:37:35,712 basehttp 6236 123145429803008 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:38:00,902 log 6236 123145429803008 Not Found: /board/1
WARNING 2020-01-02 14:38:00,903 basehttp 6236 123145429803008 "GET /board/1 HTTP/1.1" 404 2959
INFO 2020-01-02 14:38:32,477 autoreload 6236 4603387328 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 14:38:32,831 autoreload 6250 4685958592 Watching for file changes with StatReloader
WARNING 2020-01-02 14:38:51,297 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:38:51,298 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:40:36,248 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:40:36,248 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:40:36,271 log 6250 123145533542400 Not Found: /apple-touch-icon-precomposed.png
WARNING 2020-01-02 14:40:36,271 basehttp 6250 123145533542400 "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 3034
WARNING 2020-01-02 14:40:36,276 log 6250 123145533542400 Not Found: /apple-touch-icon.png
WARNING 2020-01-02 14:40:36,277 basehttp 6250 123145533542400 "GET /apple-touch-icon.png HTTP/1.1" 404 2998
WARNING 2020-01-02 14:41:31,663 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:41:31,664 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:42:05,479 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:42:05,479 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:42:06,406 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:42:06,406 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:42:06,612 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:42:06,612 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:42:06,808 log 6250 123145528287232 Not Found: /board/1
WARNING 2020-01-02 14:42:06,809 basehttp 6250 123145528287232 "GET /board/1 HTTP/1.1" 404 2959
WARNING 2020-01-02 14:42:18,315 log 6250 123145528287232 Not Found: /board/
WARNING 2020-01-02 14:42:18,315 basehttp 6250 123145528287232 "GET /board/ HTTP/1.1" 404 2956
INFO 2020-01-02 14:42:25,794 basehttp 6250 123145528287232 "GET /board/models HTTP/1.1" 301 0
ERROR 2020-01-02 14:42:25,977 log 6250 123145528287232 Internal Server Error: /board/models/
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 51, in models
    return render(request, 'classifier/board/models/models.html', {'classifiers' : classifiers})
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signup' not found. 'signup' is not a valid view function or pattern name.
ERROR 2020-01-02 14:42:25,979 basehttp 6250 123145528287232 "GET /board/models/ HTTP/1.1" 500 140033
WARNING 2020-01-02 14:42:26,116 log 6250 123145533542400 Not Found: /favicon.ico
WARNING 2020-01-02 14:42:26,117 basehttp 6250 123145533542400 "GET /favicon.ico HTTP/1.1" 404 2971
ERROR 2020-01-02 14:42:31,362 log 6250 123145528287232 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 31, in index
    return render(request, 'classifier/index.html', context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signup' not found. 'signup' is not a valid view function or pattern name.
ERROR 2020-01-02 14:42:31,364 basehttp 6250 123145528287232 "GET / HTTP/1.1" 500 135767
ERROR 2020-01-02 14:42:33,404 log 6250 123145528287232 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 31, in index
    return render(request, 'classifier/index.html', context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signup' not found. 'signup' is not a valid view function or pattern name.
ERROR 2020-01-02 14:42:33,406 basehttp 6250 123145528287232 "GET / HTTP/1.1" 500 135767
ERROR 2020-01-02 14:43:38,113 log 6250 123145528287232 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 31, in index
    return render(request, 'classifier/index.html', context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signin' not found. 'signin' is not a valid view function or pattern name.
ERROR 2020-01-02 14:43:38,114 basehttp 6250 123145528287232 "GET / HTTP/1.1" 500 134552
ERROR 2020-01-02 14:43:41,247 log 6250 123145528287232 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 31, in index
    return render(request, 'classifier/index.html', context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signin' not found. 'signin' is not a valid view function or pattern name.
ERROR 2020-01-02 14:43:41,249 basehttp 6250 123145528287232 "GET / HTTP/1.1" 500 134552
INFO 2020-01-02 14:43:53,975 basehttp 6250 123145528287232 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 14:43:53,988 basehttp 6250 123145528287232 "GET /static/css/style.css HTTP/1.1" 200 4834
ERROR 2020-01-02 14:43:56,437 log 6250 123145528287232 Internal Server Error: /board/models/
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 51, in models
    return render(request, 'classifier/board/models/models.html', {'classifiers' : classifiers})
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'createmodel' not found. 'createmodel' is not a valid view function or pattern name.
ERROR 2020-01-02 14:43:56,438 basehttp 6250 123145528287232 "GET /board/models/ HTTP/1.1" 500 153933
INFO 2020-01-02 14:44:45,565 basehttp 6250 123145528287232 "GET /board/models/ HTTP/1.1" 200 4460
ERROR 2020-01-02 14:44:47,293 log 6250 123145528287232 Internal Server Error: /board/models/create
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 65, in create
    return render(request, 'classifier/board/models/create.html', {'form' : form})
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: classifier/board/models/create.html
ERROR 2020-01-02 14:44:47,294 basehttp 6250 123145528287232 "GET /board/models/create HTTP/1.1" 500 79950
WARNING 2020-01-02 14:44:47,351 log 6250 123145533542400 Not Found: /favicon.ico
WARNING 2020-01-02 14:44:47,351 basehttp 6250 123145533542400 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 14:54:34,923 autoreload 6461 4546428352 Watching for file changes with StatReloader
ERROR 2020-01-02 14:55:41,262 log 6461 123145318158336 Internal Server Error: /board/models/create
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 65, in create
    return render(request, 'classifier/board/models/create.html', {'form' : form})
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: classifier/board/models/create.html
ERROR 2020-01-02 14:55:41,263 basehttp 6461 123145318158336 "GET /board/models/create HTTP/1.1" 500 79950
ERROR 2020-01-02 14:55:42,011 log 6461 123145318158336 Internal Server Error: /board/models/create
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 65, in create
    return render(request, 'classifier/board/models/create.html', {'form' : form})
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: classifier/board/models/create.html
ERROR 2020-01-02 14:55:42,012 basehttp 6461 123145318158336 "GET /board/models/create HTTP/1.1" 500 79950
ERROR 2020-01-02 14:55:42,427 log 6461 123145318158336 Internal Server Error: /board/models/create
Traceback (most recent call last):
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py", line 65, in create
    return render(request, 'classifier/board/models/create.html', {'form' : form})
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/myvenv/lib/python3.7/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: classifier/board/models/create.html
ERROR 2020-01-02 14:55:42,428 basehttp 6461 123145318158336 "GET /board/models/create HTTP/1.1" 500 79950
INFO 2020-01-02 14:59:33,133 basehttp 6461 123145318158336 "GET /board/models/create HTTP/1.1" 200 1949
INFO 2020-01-02 14:59:36,533 basehttp 6461 123145318158336 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 14:59:37,750 basehttp 6461 123145318158336 "GET /board/models/1 HTTP/1.1" 200 1483
WARNING 2020-01-02 14:59:37,937 log 6461 123145323413504 Not Found: /favicon.ico
WARNING 2020-01-02 14:59:37,937 basehttp 6461 123145323413504 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 14:59:39,287 basehttp 6461 123145318158336 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 14:59:40,630 basehttp 6461 123145318158336 "GET /board/models/create HTTP/1.1" 200 1949
INFO 2020-01-02 14:59:41,416 basehttp 6461 123145318158336 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 14:59:47,284 basehttp 6461 123145318158336 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 14:59:51,421 basehttp 6461 123145318158336 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 14:59:54,249 basehttp 6461 123145318158336 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 14:59:57,233 basehttp 6461 123145318158336 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 14:59:58,347 basehttp 6461 123145318158336 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 15:00:00,718 basehttp 6461 123145318158336 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 15:00:01,637 basehttp 6461 123145318158336 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 15:00:05,155 basehttp 6461 123145318158336 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 15:00:13,384 basehttp 6461 123145318158336 "GET /board/models/2 HTTP/1.1" 200 1481
WARNING 2020-01-02 15:00:13,571 log 6461 123145323413504 Not Found: /favicon.ico
WARNING 2020-01-02 15:00:13,572 basehttp 6461 123145323413504 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 15:00:15,371 basehttp 6461 123145318158336 "GET /board/models/1 HTTP/1.1" 200 1483
INFO 2020-01-02 15:00:17,698 basehttp 6461 123145318158336 "GET /board/models/3 HTTP/1.1" 200 1518
WARNING 2020-01-02 15:00:18,026 log 6461 123145323413504 Not Found: /favicon.ico
WARNING 2020-01-02 15:00:18,027 basehttp 6461 123145323413504 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 15:00:20,711 basehttp 6461 123145318158336 "GET /board/models/4 HTTP/1.1" 200 1509
WARNING 2020-01-02 15:00:20,945 log 6461 123145323413504 Not Found: /favicon.ico
WARNING 2020-01-02 15:00:20,945 basehttp 6461 123145323413504 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 15:00:46,628 autoreload 6461 4546428352 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 15:00:47,023 autoreload 6511 4516695488 Watching for file changes with StatReloader
INFO 2020-01-02 15:01:31,912 autoreload 6511 4516695488 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 15:01:32,307 autoreload 6519 4485311936 Watching for file changes with StatReloader
INFO 2020-01-02 15:01:33,059 basehttp 6519 123145471291392 "GET /board/models/2 HTTP/1.1" 200 1481
INFO 2020-01-02 15:01:34,322 basehttp 6519 123145471291392 "GET /board/models/2 HTTP/1.1" 200 1481
INFO 2020-01-02 15:01:38,249 basehttp 6519 123145471291392 "GET /board/models/2 HTTP/1.1" 200 1481
INFO 2020-01-02 15:01:39,837 basehttp 6519 123145471291392 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 15:01:41,203 basehttp 6519 123145471291392 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 15:01:42,997 basehttp 6519 123145471291392 "GET /board/models/12 HTTP/1.1" 200 1516
WARNING 2020-01-02 15:01:43,176 log 6519 123145476546560 Not Found: /favicon.ico
WARNING 2020-01-02 15:01:43,177 basehttp 6519 123145476546560 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 15:01:44,979 basehttp 6519 123145471291392 "GET /board/models/ HTTP/1.1" 200 4460
INFO 2020-01-02 15:01:46,181 basehttp 6519 123145471291392 "GET /board/models/create HTTP/1.1" 200 1949
INFO 2020-01-02 15:01:57,964 basehttp 6519 123145471291392 "POST /board/models/create HTTP/1.1" 302 0
INFO 2020-01-02 15:01:58,093 basehttp 6519 123145471291392 "GET /board/models/17 HTTP/1.1" 200 1552
WARNING 2020-01-02 15:01:58,314 log 6519 123145476546560 Not Found: /favicon.ico
WARNING 2020-01-02 15:01:58,314 basehttp 6519 123145476546560 "GET /favicon.ico HTTP/1.1" 404 2971
INFO 2020-01-02 15:02:05,310 basehttp 6519 123145471291392 "GET /board/models/ HTTP/1.1" 200 4663
INFO 2020-01-02 17:59:00,265 autoreload 6519 4485311936 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 17:59:00,666 autoreload 6748 4509920704 Watching for file changes with StatReloader
INFO 2020-01-02 17:59:24,758 autoreload 6748 4509920704 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 17:59:25,118 autoreload 6754 4716064192 Watching for file changes with StatReloader
INFO 2020-01-02 18:04:40,471 autoreload 6754 4716064192 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 18:04:40,813 autoreload 6791 4583599552 Watching for file changes with StatReloader
INFO 2020-01-02 18:07:34,435 autoreload 6791 4583599552 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 18:07:34,788 autoreload 6797 4555320768 Watching for file changes with StatReloader
INFO 2020-01-02 18:07:40,372 autoreload 6797 4555320768 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 18:07:40,759 autoreload 6801 4719578560 Watching for file changes with StatReloader
INFO 2020-01-02 18:07:53,897 autoreload 6801 4719578560 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/views.py changed, reloading.
INFO 2020-01-02 18:07:54,248 autoreload 6806 4683857344 Watching for file changes with StatReloader
INFO 2020-01-02 18:11:18,806 autoreload 6806 4683857344 /Users/satouryousuke/Documents/GitHub/MicToSoft/mic_to_soft/classifier/urls.py changed, reloading.
INFO 2020-01-02 18:11:19,252 autoreload 6822 4778974656 Watching for file changes with StatReloader
INFO 2020-01-02 18:11:21,470 basehttp 6822 123145364815872 "GET /board/models/ HTTP/1.1" 200 5250
INFO 2020-01-02 18:11:24,560 basehttp 6822 123145364815872 "GET /board/models/1 HTTP/1.1" 200 1483
INFO 2020-01-02 18:11:37,722 basehttp 6822 123145364815872 "GET /board/models/1 HTTP/1.1" 200 1483
INFO 2020-01-02 18:11:38,034 basehttp 6822 123145364815872 "GET /board/models/ HTTP/1.1" 200 5471
INFO 2020-01-02 19:12:16,634 basehttp 6822 123145364815872 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 19:12:17,787 basehttp 6822 123145364815872 "GET /board/models/ HTTP/1.1" 200 5471
INFO 2020-01-02 19:12:18,807 basehttp 6822 123145364815872 "GET /board/models/1 HTTP/1.1" 200 1483
INFO 2020-01-02 19:12:20,436 basehttp 6822 123145364815872 "GET / HTTP/1.1" 200 2280
INFO 2020-01-02 19:12:21,586 basehttp 6822 123145364815872 "GET /board/models/ HTTP/1.1" 200 5471
